# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: MongoToParse Merge Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        node-version: [16.x, 18.x, 20.x, 21.x]
        mongodb-version: ['4.4', '5.0', '6.0'] #  https://www.mongodb.com/support-policy/lifecycles
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - run: npm ci
    - run: node_modules/eslint/bin/eslint.js  --ext .ts src
    - run: node_modules/tslint/bin/tslint -p ./ -c src/tslint.json
    - run: node_modules/typescript/bin/tsc -p ./
    - run: rm -r dist
    - run: npm run coverage
      env:
        MONGODB_URI: mongodb://localhost:27017/mongoToParse
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
